<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="101.688" tests="21" failures="2" skipped="6">
  <testsuite name="Root Suite" timestamp="2023-02-23T13:02:34" tests="0" file="cypress/tests/api/core_operations/aws-terraform.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Core Operations - AWS - Terraform" timestamp="2023-02-23T13:02:34" tests="21" time="101.656" failures="2">
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Verify it gives appropriate error while trying to add existing cloud account" time="7.844" classname="DEMO - MUST - AWS - Verify it gives appropriate error while trying to add existing cloud account">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Onboard bitbucket repositories to a project" time="4.101" classname="DEMO - MUST - AWS - Onboard bitbucket repositories to a project">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Connect AWS cloud account to a project" time="0.323" classname="DEMO - MUST - AWS - Connect AWS cloud account to a project">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Trigger IaC Scan" time="10.892" classname="DEMO - MUST - AWS - Trigger IaC Scan">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Verify project scan considers all associated repos" time="0.610" classname="DEMO - MUST - AWS - Verify project scan considers all associated repos">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Verify compliant status policies" time="3.482" classname="DEMO - MUST - AWS - Verify compliant status policies">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - validate discovered resources" time="12.000" classname="DEMO - MUST - AWS - validate discovered resources">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Run cloud scan and wait until it finishes" time="0.000" classname="DEMO - MUST - AWS - Run cloud scan and wait until it finishes">
      <failure message="`cy.request()` failed on:

https://qa-milestone.cloud.aws.orgNamesecurity.com/apiHandle/v1/api/cloudscan/env/8ba69802-ae5e-42d8-b1f9-e88f081974a5/status

The response we received from your web server was:

  &gt; 500: Internal Server Error

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://qa-milestone.cloud.aws.orgNamesecurity.com/apiHandle/v1/api/cloudscan/env/8ba69802-ae5e-42d8-b1f9-e88f081974a5/status
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;x-cookie&quot;: &quot;token=961837a6c832a79d343861ef4bbd18e318ce27f6cdfab0add9e44c6e49fed6ee&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/12.6.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;*/*&quot;,
  &quot;cookie&quot;: &quot;nginx-cloud-site-id=qa-milestone&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;
}

-----------------------------------------------------------

The response we got was:

Status: 500 - Internal Server Error
Headers: {
  &quot;date&quot;: &quot;Thu, 23 Feb 2023 13:03:24 GMT&quot;,
  &quot;content-type&quot;: &quot;application/json; charset=utf-8&quot;,
  &quot;content-length&quot;: &quot;146&quot;,
  &quot;connection&quot;: &quot;keep-alive&quot;,
  &quot;set-cookie&quot;: [
    &quot;nginx-cloud-site-id=qa-milestone; path=/; HttpOnly; SameSite=Strict; Secure&quot;
  ],
  &quot;vary&quot;: &quot;origin&quot;,
  &quot;cache-control&quot;: &quot;no-store&quot;,
  &quot;x-request-uuid&quot;: &quot;\&quot;79edf68b38865bc06b06f4d8ee2d85fa\&quot;&quot;,
  &quot;x-xss-protection&quot;: &quot;1; mode=block&quot;,
  &quot;x-frame-options&quot;: &quot;DENY&quot;,
  &quot;strict-transport-security&quot;: &quot;max-age=63072000; includeSubDomains&quot;,
  &quot;x-content-type-options&quot;: &quot;nosniff&quot;,
  &quot;x-gateway-site-id&quot;: &quot;service-nginx-router-us-east-1-eng-bf9cb6c69-lvgrb&quot;,
  &quot;pragma&quot;: &quot;no-cache&quot;,
  &quot;expect-ct&quot;: &quot;enforce, max-age=86400&quot;,
  &quot;x-path-handler&quot;: &quot;orgName-io&quot;
}
Body: {
  &quot;statusCode&quot;: 500,
  &quot;error&quot;: &quot;Internal Server Error&quot;,
  &quot;message&quot;: &quot;An internal server error occurred. Please wait a moment and try your request again.&quot;
}


https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

https://qa-milestone.cloud.aws.orgNamesecurity.com/apiHandle/v1/api/cloudscan/env/8ba69802-ae5e-42d8-b1f9-e88f081974a5/status

The response we received from your web server was:

  > 500: Internal Server Error

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://qa-milestone.cloud.aws.orgNamesecurity.com/apiHandle/v1/api/cloudscan/env/8ba69802-ae5e-42d8-b1f9-e88f081974a5/status
Headers: {
  "Connection": "keep-alive",
  "x-cookie": "token=961837a6c832a79d343861ef4bbd18e318ce27f6cdfab0add9e44c6e49fed6ee",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/12.6.0 Chrome/106.0.5249.51 Electron/21.0.0 Safari/537.36",
  "accept": "*/*",
  "cookie": "nginx-cloud-site-id=qa-milestone",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 500 - Internal Server Error
Headers: {
  "date": "Thu, 23 Feb 2023 13:03:24 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "146",
  "connection": "keep-alive",
  "set-cookie": [
    "nginx-cloud-site-id=qa-milestone; path=/; HttpOnly; SameSite=Strict; Secure"
  ],
  "vary": "origin",
  "cache-control": "no-store",
  "x-request-uuid": "\"79edf68b38865bc06b06f4d8ee2d85fa\"",
  "x-xss-protection": "1; mode=block",
  "x-frame-options": "DENY",
  "strict-transport-security": "max-age=63072000; includeSubDomains",
  "x-content-type-options": "nosniff",
  "x-gateway-site-id": "service-nginx-router-us-east-1-eng-bf9cb6c69-lvgrb",
  "pragma": "no-cache",
  "expect-ct": "enforce, max-age=86400",
  "x-path-handler": "orgName-io"
}
Body: {
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred. Please wait a moment and try your request again."
}


https://on.cypress.io/request
    at <unknown> (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:139725:80)
    at tryCatcher (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:8914:23)
    at Promise._settlePromiseFromHandler (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:6849:31)
    at Promise._settlePromise (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:6906:18)
    at Promise._settlePromise0 (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:6951:10)
    at Promise._settlePromises (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:7031:18)
    at _drainQueueStep (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:3621:12)
    at _drainQueue (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:3614:9)
    at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:3630:5)
    at Async.drainQueues (https://qa-milestone.cloud.aws.orgNamesecurity.com/__cypress/runner/cypress_runner.js:3500:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/tests/api/core_operations/aws-terraform.spec.js:124:8)]]></failure>
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Validate Violations" time="17.371" classname="DEMO - MUST - AWS - Validate Violations">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Validate Drifts" time="0.000" classname="DEMO - MUST - AWS - Validate Drifts">
      <failure message="expected 0 to be above 0" type="AssertionError"><![CDATA[AssertionError: expected 0 to be above 0
    at Context.eval (webpack:///./cypress/requests/env.js:446:51)

      + expected - actual

]]></failure>
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Create BitBucket PR with reviewer" time="5.464" classname="DEMO - MUST - AWS - Create BitBucket PR with reviewer">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform DEMO - MUST - AWS - Create Github PR with reviewer (HACKY: creating Github PR through Bitbucket IaC env)" time="4.787" classname="DEMO - MUST - AWS - Create Github PR with reviewer (HACKY: creating Github PR through Bitbucket IaC env)">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform AWS - DEMO - MUST - Create ADO PR without reviewer (HACKY: creating ADO PR through Bitbucket IaC env)" time="5.086" classname="AWS - DEMO - MUST - Create ADO PR without reviewer (HACKY: creating ADO PR through Bitbucket IaC env)">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform MUST - AWS - Validate k8s cluster counts " time="0.341" classname="MUST - AWS - Validate k8s cluster counts ">
    </testcase>
    <testcase name="Core Operations - AWS - Terraform MUST - Check if Global Repos are paginated" time="1.701" classname="MUST - Check if Global Repos are paginated">
    </testcase>
  </testsuite>
</testsuites>